#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill --randomize /data/Pictures/Wallpapers/* &
picom --config /home/itami/.config/picom/picom.conf &
~/.config/polybar/launch.sh &
~/kbd_backlight.sh &
volctl &
# redshift -l 0.3555505:-78.1245219 &
wmname LG3D

xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --mode 1360x768 --rotate normal --right-of eDP-1

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
# bspc monitor eDP-1 -n monitor0 -d 1 2 3 4 5
# bspc monitor HDMI-1 -n monitor1 -d 6 7 8 9 0
# bspc monitor eDP-1 -s HDMI-1 

bspc config border_width         3
bspc config window_gap           10
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#ebcb8b"

# bspc rule -a Alacritty desktop='^1' follow=on
bspc rule -a Brave-browser desktop='^8' follow=on
bspc rule -a Notion desktop='^9' follow=on
bspc rule -a obsidian desktop='^9' follow=on
bspc rule -a Google-chrome desktop='^7' follow=on
bspc rule -a "Microsoft Teams - Preview" desktop='^10' follow=on
bspc rule -a TelegramDesktop desktop='^7' follow=on
bspc rule -a Zathura state=tiled
bspc rule -a ulauncher state=floating
bspc rule -a "Ulauncher - Application Launcher" state=floating
bspc rule -a obs desktop='^6' follow=on
bspc rule -a mpv desktop='^9' follow=on

# obsidian &
echo "------------" > ~/htbMachine
